language: node_js
node_js:
  - '0.6'
  - '0.8'
  - '0.10'
  - '0.12'
  - '1.8'
  - '2.5'
  - '3.3'
  - '4.2.0' # Test timers regression
  - '4.4'
  - '5.11'
  - '6.2'

sudo: false

notifications:
  email: false

cache:
  directories:
    - node_modules

services:
  - mysql
install:
  - npm install

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - mysql -e 'create database db_recontime;'

script:
- npm run ci